backend:
  name: github
  repo: lx-es/lx-es.github.io   # 替换为你的 GitHub 用户名和仓库名
  branch: master              # 如有需要可调整分支
  auth_scope: public_repo       # 或 private_repo，根据实际仓库权限
  identity_url: "https://life-es.netlify.app/.netlify/identity"
  app_id: ${CLIENT_ID}
  app_secret: ${CLIENT_SECRET}

media_folder: "static/images"    # 上传的图片将存储在此目录
public_folder: "/images"         # 在网站中引用图片的相对路径

# 配置 Cloudinary 作为媒体库
media_library:
  name: cloudinary
  config:
    cloud_name: lifejuan        # 替换为你在 Cloudinary 的云名称
    api_key: 431433219326673    # 替换为 Cloudinary API key
    upload_preset: Unsigned     # 替换为你创建的 Upload Preset

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "摘要", name: "summary", widget: "text" }
      - { label: "正文", name: "body", widget: "markdown" }
